Script started on Thu 05 Oct 2017 05:49:06 PM EDT
> /home/mcube/rgrasp/catkin_ws/src/apc_planning/src/planner17.py(16)<module>()
-> from item import Item
(Pdb) c
FAILED TO IMPORT VISION, WILL ONLY RUN IN VIRTUAL
FAILED TO IMPORT VISION, WILL ONLY RUN IN VIRTUAL
[ PLANNER ] visionType  =  real
[ PLANNER ] in_simulation  =  False
[ PLANNER ] combined_task  =  False
[ PLANNER ] decider  =  baseline
[ PLANNER ] experiment  =  False
Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "planner17.py", line 16, in <module>
    from item import Item
  File "planner17.py", line 2805, in run
    self.webpage.updateValue('TaskName', 'Stowing')
AttributeError: 'TaskPlanner' object has no attribute 'webpage'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/mcube/rgrasp/catkin_ws/src/apc_planning/src/planner17.py(2805)run()
-> self.webpage.updateValue('TaskName', 'Stowing')
(Pdb) 